# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "pypsa-earth"
SPDX-PackageSupplier = "The PyPSA-Earth and PyPSA-Eur Authors <pypsameetsearth@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/pypsa-meets-earth/pypsa-earth"

[[annotations]]
path = "doc/data.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "doc/configtables/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "test/utils/agg_p_nom_minmax.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/agg_p_nom_minmax.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/industry/ammonia_plants.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "doc/assets/images/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "doc/assets/scripts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "pixi.lock"
precedence = "override"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "files/**.tif"
precedence = "aggregate"
SPDX-FileCopyrightText = "PyPSA-GH Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "files/**.parquet"
precedence = "aggregate"
SPDX-FileCopyrightText = "PyPSA-GH Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "*.parquet"
precedence = "aggregate"
SPDX-FileCopyrightText = "PyPSA-GH Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "resources/osm/clean/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "PyPSA-GH Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "resources/shapes/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "PyPSA-GH Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "notebooks/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "PyPSA-GH Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "docs/Makefile"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/make.bat"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/conf.py"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/requirements.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/index.rst"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/getting_started/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/tutorials/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"
